# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
name: seyler
version: '0.0.0'
github: "zekzekus/seyler"
license: MIT
author: "Zekeriya Koc"
maintainer: "Zekeriya Koc"
synopsis: Command line interface for Things productivitiy app
description: Command line interface for Things productivitiy app
category: Other

extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml

ghc-options:
  - -Wall
  - -Wcompat
  - -Wincomplete-record-updates
  - -Wincomplete-uni-patterns
  - -Wredundant-constraints
default-extensions:  OverloadedStrings, NoImplicitPrelude

dependencies:
  - protolude
  - text

library:
  dependencies:
  - base
  source-dirs: library

executables:
  seyler:
    source-dirs: executable
    main: Main.hs
    dependencies:
    - base
    - seyler
    - process
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N

tests:
  seyler-test-suite:
    source-dirs: test-suite
    main: Main.hs
    dependencies:
    - base
    - seyler
    - tasty
    - tasty-hspec
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
